name: Build LaTeX project

on:
  push:
    tags:
      - 'v*'


jobs:
  build_job:
    permissions: write-all
    runs-on: ubuntu-22.04
    env:
      PDF_FILENAME: poster-mardi-open-interfaces-${{ github.ref_name }}.pdf
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: mardi-annual-meeting-2024-open-interfaces.tex

      - name: Rename PDF file
        run: mv mardi-annual-meeting-2024-open-interfaces.pdf poster-mardi-open-interfaces-${{ github.ref_name }}.pdf

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: poster-mardi-open-interfaces-${{ github.ref_name }}.pdf

